export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

export const FETCH_CLASSES = 'FETCH_CLASSES';
export const FETCH_CLASSES_SUCCESS = 'FETCH_CLASSES_SUCCESS';
export const FETCH_CLASSES_ERROR = 'FETCH_CLASSES_ERROR';

export const FETCH_SECTIONS = 'FETCH_SECTIONS';
export const FETCH_SECTIONS_SUCCESS = 'FETCH_SECTIONS_SUCCESS';
export const FETCH_SECTIONS_ERROR = 'FETCH_SECTIONS_ERROR';

export const FETCH_SUBJECTS = 'FETCH_SUBJECTS';
export const FETCH_SUBJECTS_SUCCESS = 'FETCH_SUBJECTS_SUCCESS';
export const FETCH_SUBJECTS_ERROR = 'FETCH_SUBJECTS_ERROR';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const ADVERTISEMENT_FETCH = 'ADVERTISEMENT_FETCH';
export const ADVERTISEMENT_FETCH_SUCCESS = 'ADVERTISEMENT_FETCH_SUCCESS';
export const ADVERTISEMENT_FETCH_ERROR = 'ADVERTISEMENT_FETCH_ERROR';

export const ADVERTISEMENT_CREATE = 'ADVERTISEMENT_CREATE';
export const ADVERTISEMENT_CREATE_SUCCESS = 'ADVERTISEMENT_CREATE_SUCCESS';
export const ADVERTISEMENT_CREATE_ERROR = 'ADVERTISEMENT_CREATE_ERROR';

export const ADVERTISEMENT_UPDATE = 'ADVERTISEMENT_UPDATE';
export const ADVERTISEMENT_UPDATE_SUCCESS = 'ADVERTISEMENT_UPDATE_SUCCESS';
export const ADVERTISEMENT_UPDATE_ERROR = 'ADVERTISEMENT_UPDATE_ERROR';

export const ADVERTISEMENTS_LIST_FETCH = 'ADVERTISEMENTS_LIST_FETCH';
export const ADVERTISEMENTS_LIST_FETCH_SUCCESS = 'ADVERTISEMENTS_LIST_FETCH_SUCCESS';
export const ADVERTISEMENTS_LIST_FETCH_ERROR = 'ADVERTISEMENTS_LIST_FETCH_ERROR';

export const ADVERTISEMENT_VIEW = 'ADVERTISEMENT_VIEW';
export const ADVERTISEMENT_VIEW_SUCCESS = 'ADVERTISEMENT_VIEW_SUCCESS';
export const ADVERTISEMENT_VIEW_ERROR = 'ADVERTISEMENT_VIEW_ERROR';
